# -*- coding: utf-8 -*-
"""assign3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19uwpbtAdpLso2D1tycDzY2F52r9zCyJ5
"""

#Question1:


import numpy as np
K=np.array([1,2,3,4])
L=np.array([5.5,6.5,7.5,8.5])
print(np.add(K,L))

    
print(np.subtract(K,L))

print(np.multiply(K,L))

print(np.divide(K,L))

#Question2:

X = np.array([[1,2],[3,4]])
print(np.sqrt(X))

print(np.min(X,axis=1))

print(np.max(X,axis=1))

print(np.min(X,axis=0))

print(np.max(X,axis=0))

print(X.std())

print(np.exp(X))

print(X.mean())

print(np.median(X))